
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xuixhcikcnqnjyxizwux.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh1aXhoY2lrY25xbmp5eGl6d3V4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzNjUwNTMsImV4cCI6MjA1Njk0MTA1M30.XUws17-Qw0FeuvhPE4-PcuD3vK1zTZ30hDqnJJAjix8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      storageKey: 'supabase.auth.token',
      autoRefreshToken: true,
      detectSessionInUrl: true,
      storage: localStorage
    }
  }
);
